
modLoader="javafml" #mandatory
loaderVersion="[39,)"
license="GNU GPLv3 "
[[mods]]
modId="ambidextrous"
version="${file.jarVersion}"
displayName="Ambidextrous"
logoFile=""
credits="AlgorithmX2"
authors="AlgorithmX2, Helimyne"
description="a mod about using two keybinds for each hand."
[[dependencies.ambidextrous]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ambidextrous]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
